fix: PrimaryIdentifier: fix clear_input_attributes
The clear_input_attributes functionality in the PrimaryIdentifier MicroService breaks with:

    AttributeError: '<class 'satosa.internal.InternalData'>' object has no attribute 'attribute_names'

on line logging the attributes being cleared:

	msg = "{} Clearing values for these input attributes: {}".format(
	    logprefix, data.attribute_names
	)

As the actual attribute store (dict) being cleared is `data.attributes`,
the best fix appears to be to log the keys in the dict - attribute names:

    logprefix, data.attributes.keys()